### ISSUE TITLE
Incorrect copyright dates in license.json files.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/soccer-common#14]
While working on renaming localized image files for https://github.com/phetsims/joist/issues/953,  I've noticed that most of the dates in license.json files appear to be incorrect. For example, every entry in images/africa/license.json is Copyright 2022, but none of the image in images/africa/ existed until 2023.

**Comment by samreid** [comment]
@marlitas should we change the dates in the license.json file?

**Comment by pixelzoom** [comment]
While working on #13, I change "Copyright 2062" (?!) to "Copyright 2024" throughout africaModest/license.json.  See https://github.com/phetsims/soccer-common/commit/e27823b3c8627a3ed8f31737c53f58cf5763457d.

**Comment by Luisav1** [comment]
I noticed the images were added in 2024 here: https://github.com/phetsims/soccer-common/commit/1513f6a083aaf767caae4f7a6664640b2d471f5a. Since it was a quick fix, I updated the copyright dates while working on them in https://github.com/phetsims/soccer-common/issues/10. Let me know if you have any concerns, thanks! Leaving this open for your review @marlitas.

**Comment by marlitas** [comment]
I think this is fine. Thanks for the fix @Luisav1!
