### ISSUE TITLE
Consolidate common strings from MSaB and C&V

### ISSUE THREAD

**Issue by jbphet** [phetsims/soccer-common#15]
There is at least one string that refers to soccer balls and appears in both the "Mean: Share & Balance" sim and the "Center & Variability" sim.  We should consolidate this and any other strings that are likely to be shared in `soccer-common-strings_en.json`.  @marlitas and I started on this, and added one string, but we ran into difficulties so it isn't actually used yet in MSaB or C&V.

**Comment by jbphet** [comment]
Note that consolidating this will involve moving existing translations from C&V.

**Comment by marlitas** [comment]
We need to address this before the upcoming dev test. Removing off of hold.

**Comment by marlitas** [comment]
@marlitas will identify what duplicate strings exist between CAV and MSAB that can be consolidated and need to be moved.

**Comment by marlitas** [comment]
Duplicated strings in soccer-common and center-and-variability:
```
"needAtLeastOneKick": {
    "value": "Need at least one kick"
  }
```

Duplicated strings in mean-share-and-balance and center-and-variability:
```
 "mean": {
    "value": "Mean"
  },
"predictMean": {
    "value": "Predict Mean"
  },
```

There's not that many... not sure if that makes it more or less worth it.

**Comment by marlitas** [comment]
In slack the following conversation occurred:

****************************
Chris Malley
  1 hour ago
+1 to leave as is, duplicate the strings. It’s not the ideal solution, but it’s the most practical given the current constraints and costs associated with relocating strings. (edited) 


Chris Malley
  [1 hour ago](https://phetsims.slack.com/archives/C05TB6YSP46/p1720023694829009?thread_ts=1720023455.841469&cid=C05TB6YSP46)
And if you put the duplicates in soccer-common instead of MSaB, then you’ve addressed the needs of future sims in the suite.  With a path forward for eventually removing the duplicates from CaV (create a deferred GitHub issue). (edited) 


Kathy Perkins
  [1 hour ago](https://phetsims.slack.com/archives/C05TB6YSP46/p1720023822323719?thread_ts=1720023455.841469&cid=C05TB6YSP46)
:point_up:I like Chris' solution here. Leave CAV alone, but put the new strings (used only by MSaB at the moment) in soccer common for any future sims. So no change to CAV on main - its not using those strings. Eventually swap if CAV is refactored to leverage them.


Chris Malley
  [1 hour ago](https://phetsims.slack.com/archives/C05TB6YSP46/p1720024230923329?thread_ts=1720023455.841469&cid=C05TB6YSP46)
And create a GitHub issue in the CAV repo identifying which strings should be switched over to soccer-common the next time that CAV is published from a new release branch.
************************

Therefore I am going to move strings that seem like they should belong in soccer-common to the soccer-common strings file, and create an issue in CAV.

**Comment by marlitas** [comment]
Issue was created and strings were moved over to soccer-common. I believe this is ready to close, but I'll hand it off to @jbphet for a final check.

**Comment by jbphet** [comment]
I'm good with the plan of leaving C&V alone for now.  I've added [a comment to the issue there](https://github.com/phetsims/center-and-variability/issues/624#issuecomment-2215448985), and I think we are good to go for MS&B.  Closing.
