### ISSUE TITLE
Selected group item should not change while sorting

### ISSUE THREAD

**Issue by zepumph** [phetsims/soccer-common#7]
From https://github.com/phetsims/scenery-phet/issues/815, promoting a TODO to an issue in GroupSortInteractionModel:

```
    // TODO: Turn this on! But we can't until reorganizeStack respects the selection first. https://github.com/phetsims/scenery-phet/issues/815
    // assert && this.selectedGroupItemProperty.lazyLink( () => {
    //   assert && assert( !this.isGroupItemKeyboardGrabbedProperty.value, 'should not change selection when sorting' );
    // } );

```

Over to @marlitas and @jbphet. Good luck!

**Comment by marlitas** [comment]
I addressed this above. 

The main issue was that we were changing the value of the `selectedGroupItem` even if it was not part of the stack that had changed. This was especially problematic in the `valueProperty` link in `SoccerSceneModel` because we first organize the old stack we left from, and then add our selected ball to the end of the new stack array which puts it at the top of the stack. It had not been added to the new stack array yet so it was out of order when the stackChangedEmitter fired switching our `selectedGroupItem` in the process.


It would be good to have this reviewed since I'm not convinced I didn't miss an edge case, but it feels more maintainable and considerably less invasive than the alternatives.

**Comment by marlitas** [comment]
@jbphet let me know if you want to do this synchronously.

**Comment by jbphet** [comment]
I've looked over the changes and have a basic understanding of the problem and solution, but above @marlitas said:

> @jbphet let me know if you want to do this synchronously.

I think it would be worthwhile to discuss over Zoom, since it would increase my confidence that I understand what's going on.

**Comment by jbphet** [comment]
@marlitas and I just met over Zoom and talked through this change.  I now better understand the essence of the original problem and the way in which it was addressed, and she still feels reasonably confident in the fix after walking me through it.  I think that's sufficient, so I'll go ahead and close this.
